version: '2.2'
services:
  job:
    build:
      context: .
      target: final
    working_dir: /tmp
    command: ["./money-tracker"]
    volumes:
      - ${PWD}/.env:/tmp/.env:ro
      - ${PWD}/urls.json:/tmp/urls.json:ro